export const countryName=[
    {"countrySortName":'in', "countryName" : "India"},
    {"countrySortName":'us', "countryName" : "USA"},
    {"countrySortName":'ch', "countryName" : "Switzerland"},
    {"countrySortName":"ae", "countryName" : "United Arab Emirates"},
    {"countrySortName":"ar", "countryName" : "Argentina"},
    {"countrySortName":"at", "countryName" : "Austria"},
    {"countrySortName":"au", "countryName" : "Australia"},
    {"countrySortName":"be", "countryName" : "Belgium"},
    {"countrySortName":"bg", "countryName" : "Bulgaria"},
    {"countrySortName":"br", "countryName" : "Brazil"},
    {"countrySortName":"ca", "countryName" : "Canada"},
    {"countrySortName":"cn", "countryName" : "China"},
    {"countrySortName":"co", "countryName" : "Colombia"},
    {"countrySortName":"cu", "countryName" : "Cuba"},
    {"countrySortName":"cz", "countryName" : "Czechia"},
    {"countrySortName":"de", "countryName" : "Germany"},
    {"countrySortName":"eg", "countryName" : "Egypt"},
    {"countrySortName":"fr", "countryName" : "France"},
    {"countrySortName":"gb", "countryName" : "United Kingdom"},
    {"countrySortName":"gr", "countryName" : "Greece"},
    {"countrySortName":"hk", "countryName" : "Hong Kong"},
    {"countrySortName":"hu", "countryName" : "Hungary"},
    {"countrySortName":"id", "countryName" : "Indonesia"},
    {"countrySortName":"ie", "countryName" : "Ireland"},
    {"countrySortName":"il", "countryName" : "Israel"},    
    {"countrySortName":"it", "countryName" : "Italy"},
    {"countrySortName":"jp", "countryName" : "Japan"},
    {"countrySortName":"kr", "countryName" : "Korea"},
    {"countrySortName":"lt", "countryName" : "Lithuania"},
    {"countrySortName":"lv", "countryName" : "Latvia"},
    {"countrySortName":"ma", "countryName" : "Morocco"},
    {"countrySortName":"mx", "countryName" : "Mexico"},
    {"countrySortName":"my", "countryName" : "Malaysia"},
    {"countrySortName":"ng", "countryName" : "Nigeria"},
    {"countrySortName":"nl", "countryName" : "Netherlands"},
    {"countrySortName":"no", "countryName" : "Norway"},
    {"countrySortName":"nz", "countryName" : "New Zealand"},
    {"countrySortName":"ph", "countryName" : "Philippines"}, 
    {"countrySortName":"pl", "countryName" : "Poland"},
    {"countrySortName":"pt", "countryName" : "Portugal"},
    {"countrySortName":"ro", "countryName" : "Romania"},
    {"countrySortName":'rs', "countryName" : "Serbia"},
    {"countrySortName":"ru", "countryName" : "Russian Federation"},
    {"countrySortName":"sa", "countryName" : "Saudi Arabia"},
    {"countrySortName":"se", "countryName" : "Sweden"},
    {"countrySortName":"sg", "countryName" : "Singapore"},
    {"countrySortName":"si", "countryName" : "Slovenia"},
    {"countrySortName":"sk", "countryName" : "Slovakia"},
    {"countrySortName":"th", "countryName" : "Thailand"},
    {"countrySortName":"tr", "countryName" : "Türkiye"},
    {"countrySortName":"tw", "countryName" : "Taiwan"},
    {"countrySortName":"ua", "countryName" : "Ukraine"},
    {"countrySortName":"ve", "countryName" : "Venezuela"},
    {"countrySortName":"za", "countryName" : "South Africa"}
]

export const countryObject={
    'in' : "India",
    'us' : "USA",
    'ch' : "Switzerland",
    "ae" : "United Arab Emirates",
    "ar" : "Argentina",
    "at" : "Austria",
    "au" : "Australia",
    "be" : "Belgium",
    "bg" : "Bulgaria",
    "br" : "Brazil",
    "ca" : "Canada",
    "cn" : "China",
    "co" : "Colombia",
    "cu" : "Cuba",
    "cz" : "Czechia",
    "de" : "Germany",
    "eg" : "Egypt",
    "fr" : "France",
    "gb" : "United Kingdom",
    "gr" : "Greece",
    "hk" : "Hong Kong",
    "hu" : "Hungary",
    "id" : "Indonesia",
    "ie" : "Ireland",
    "il" : "Israel",    
    "it" : "Italy",
    "jp" : "Japan",
    "kr" : "Korea",
    "lt" : "Lithuania",
    "lv" : "Latvia",
    "ma" : "Morocco",
    "mx" : "Mexico",
    "my" : "Malaysia",
    "ng" : "Nigeria",
    "nl" : "Netherlands",
    "no" : "Norway",
    "nz" : "New Zealand",
    "ph" : "Philippines", 
    "pl" : "Poland",
    "pt" : "Portugal",
    "ro" : "Romania",
    'rs' : "Serbia",
    "ru" : "Russian Federation",
    "sa" : "Saudi Arabia",
    "se" : "Sweden",
    "sg" : "Singapore",
    "si" : "Slovenia",
    "sk" : "Slovakia",
    "th" : "Thailand",
    "tr" : "Türkiye",
    "tw" : "Taiwan",
    "ua" : "Ukraine",
    "ve" : "Venezuela",
    "za" : "South Africa"
}